source 'https://rubygems.org'
git_source(:github) { |repo| "https://github.com/#{repo}.git" }

ruby '2.5.1'


gem 'rails', '~> 5.2.2'
gem 'listen'

gem 'uglifier', '>= 1.3.0'
gem 'jquery-rails'
#gem 'puma', '~> 3.11'

group :development, :test do
  gem 'byebug'
  gem 'sqlite3'
end

group :development do
  gem 'web-console', '>= 3.3.0'
end

