source 'https://rubygems.org'
git_source(:github) { |repo| "https://github.com/#{repo}.git" }

ruby '2.5.1'

gem 'rails', '~> 5.2.2'
gem 'sqlite3', '~>1.3.6'
gem 'jquery-rails'

group :development, :test do
  gem 'byebug'
  gem 'listen'
end

group :development do
  gem 'listen'
  gem 'web-console', '>= 3.3.0'
end

